---
title: "Ch 3+4"
author: "Amalie Lysgaard Andersen"
date: "21/2/2019"
output: html_document
---


```{r}
library(pacman)
p_load("coda", "mvtnorm", "devtools", "rstan", "rethinking")

```

```{r Compute posterior using grid approximation} 
# Compute posterior using grid approximation

p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep( 1 , 1000 )
likelihood <- dbinom( 6 , size=9 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)

# Drawing 10,000 samples from posterior (1e4 is 10,000)
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
plot(samples)

#DEnsity estimate from ^these samples
dens( samples )
```

```{r Compute Percentile Intervals (PI)}
# Compute Percentile Intervals (PI)
PI(samples, prob = 0.5)

# Comoute HPDI
HPDI(samples, prob=0.5)

# Compute MAP (parameter value with highest posterior probability) --> a point estimate which summarises the posterior
p_grid[ which.max(posterior)]

```

```{r Dummy data --> simulating samples}
# arises from binomial distrbutions --> this function picks randomly
rbinom( 1 , size=2 , prob=0.7 )
rbinom( 1e5 , size=2 , prob=0.7 )

dummy_w <- rbinom( 1e5 , size=9 , prob=0.7 ) # 9 tosses
simplehist( dummy_w , xlab="dummy water count" ) 
```


### CHAPTER 4

```{r Normal distrbution - multiplication}
prod( 1 + runif(12,0,0.1) )
growth <- replicate( 10000 , prod( 1 + runif(12,0,0.1) ) )
dens( growth , norm.comp=TRUE )
```

```{r Gaussian model of height}
d <- data(Howell1) 
d <- Howell1

#filtering out age over 18
d2 <- d[ d$age >= 18 , ]

#height distribution
dens(d2$height)

#plotting the prior
curve( dnorm( x , 178 , 20 ) , from=100 , to=250 ) #mean height 178, 20 SD

#sd prior
curve( dunif( x , 0 , 50 ) , from=-10 , to=60 )

# simulating heights by sampling from priors
sample_mu <- rnorm( 1e4 , 178 , 20 )
sample_sigma <- runif( 1e4 , 0 , 50 )
prior_h <- rnorm( 1e4 , sample_mu , sample_sigma )
dens( prior_h )

### grid approximation
mu.list <- seq( from=140, to=160 , length.out=200 )
sigma.list <- seq( from=4 , to=9 , length.out=200 )
post <- expand.grid( mu=mu.list , sigma=sigma.list )
post$LL <- sapply( 1:nrow(post) , function(i) sum( dnorm(
                d2$height ,
                mean=post$mu[i] ,
                sd=post$sigma[i] ,
                log=TRUE ) ) )
post$prod <- post$LL + dnorm( post$mu , 178 , 20 , TRUE ) +
    dunif( post$sigma , 0 , 50 , TRUE )
post$prob <- exp( post$prod - max(post$prod) )

contour_xyz( post$mu , post$sigma , post$prob )
image_xyz( post$mu , post$sigma , post$prob )

# sampling
sample.rows <- sample( 1:nrow(post) , size=1e4 , replace=TRUE ,
    prob=post$prob )
sample.mu <- post$mu[ sample.rows ]
sample.sigma <- post$sigma[ sample.rows ]

plot( sample.mu , sample.sigma , cex=0.5 , pch=16 , col=col.alpha(rangi2,0.1) ) #cex = size of points, pch = point character

#density plots of samples
dens( sample.mu )
dens( sample.sigma )

#hpdi's
HPDI( sample.mu )
HPDI( sample.sigma )
```

```{r Quadratic approximation to a model}
#reloading data 
library(rethinking)
data(Howell1)
d <- Howell1
d2 <- d[ d$age >= 18 , ]

# defining model
flist <- alist(
    height ~ dnorm( mu , sigma ) ,
    mu ~ dnorm( 178 , 20 ) ,
    sigma ~ dunif( 0 , 50 )
)

#fit model to data
m4.1 <- map( flist , data=d2 )

#ooking at the MAP of our model
precis( m4.1 )

```

```{r sampling from a map fit}
#variance-corvariance matrix
vcov( m4.1 )

# sampling vectors of values from a multi-dimensional Gaussian distribution
post <- extract.samples( m4.1 , n=1e4 )
head(post)
precis(post)
```

```{r plot}
# plotting weight and height
plot( d2$height ~ d2$weight )
```

```{r Map model fitting - new predictor}
# load data again, since it's a long way back 
data(Howell1)
d <- Howell1
d2 <- d[ d$age >= 18 , ]

# fit model
m4.3 <- map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b*weight ,
        a ~ dnorm( 156 , 100 ) ,
        b ~ dnorm( 0 , 10 ) ,
        sigma ~ dunif( 0 , 50 )
), data=d2 )

#inspcting data
precis(m4.3)
#Since β is a slope, the value 0.90 can be read as a person 1 kg heavier is expected to be 0.90 cm taller
#The estimate of α, a in the precis table, indicates that a person of weight 0 should be 114cm tall
#the estimate for σ, sigma, informs us of the width of the distribution of heights around the mean. A quick way to interpret it is to recall that about 95% of the probability in a Gaussian distribution lies between two standard deviations. So in this case, the estimate tells us that 95% of plausible heights lie within 10cm (2σ) of the mean height


```

```{r Centering: counteracting strong correlations}
#variance-covariance correlation matrix (correlation among parameters)
precis(m4.3, corr =T)

#centered version of weight variable
d2$weight.c <- d2$weight - mean(d2$weight)

#refitting to model
m4.4 <- map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b*weight.c ,
        a ~ dnorm( 178 , 100 ) ,
        b ~ dnorm( 0 , 10 ) ,
sigma ~ dunif( 0 , 50 ) ),
data=d2 )

#new corr matrix 
precis(m4.4, corr =T)
#The estimate for the intercept, α, still means the same thing it did before: the expected value of the outcome variable, when the predictor variable is equal to zero. But now the mean value of the predictor is also zero. So the intercept also means: the expected value of the outcome, when the predictor is at its average value. This makes interpreting the intercept a lot easier.

```

```{r plotting posterior inference against data}
#superimposing the MAP values over the height and weight data
plot( height ~ weight , data=d2 )
#Adding a map line = the posterior mean
abline( a=coef(m4.3)["a"] , b=coef(m4.3)["b"] )

# visualising uncertainty by extracling sample lines from posterior distribution
post <- extract.samples( m4.3 )

#The following code extracts the first 10 cases and re-estimates the model:
N <- 10
dN <- d2[ 1:N , ]
mN <- map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b*weight ,
        a ~ dnorm( 178 , 100 ) ,
        b ~ dnorm( 0 , 10 ) ,
        sigma ~ dunif( 0 , 50 )
) , data=dN )

###now plotting 20 lines to show uncertainty
# extract 20 samples from the posterior
post <- extract.samples( mN , n=20 )
# display raw data and sample size
plot( dN$weight , dN$height ,
    xlim=range(d2$weight) , ylim=range(d2$height) ,
    col=rangi2 , xlab="weight" , ylab="height" )
mtext(concat("N = ",N))
# plot the lines, with transparency
for  (i in 1:20) 
   ( abline( a=post$a[i] , 
            b=post$b[i] , 
            col=col.alpha("black",0.3) )
```

```{r plotting interval around regression line}
#make a list of 10,000 values of μ for an individual who weighs 50 kilograms
mu_at_50 <- post$a + post$b * 50

#plotting density for ^this vector of means
dens( mu_at_50 , col=rangi2 , lwd=2 , xlab="mu|weight=50")

### finding HPDI
HPDI( mu_at_50 , prob=0.89 )
#89% of the ways for the model to produce the data place the average height between about 159 cm and 160 cm (conditional on the model and data), assuming the weight is 50 kg.

### repeat the above calculation for every weight value on the horizontal axis, not just when it is 50 kg
mu <- link( m4.3 )
str(mu)
#What link will do is take your map model fit, sample from the posterior distribution, and then compute μ for each case in the data and sample from the posterior distribution

#distribution of μ for each unique weight value on the horizontal axis
# define sequence of weights to compute predictions for
# these values will be on the horizontal axis
weight.seq <- seq( from=25 , to=70 , by=1 )
# use link to compute mu
# for each sample from posterior
# and for each weight in weight.seq
mu <- link( m4.3 , data=data.frame(weight=weight.seq) )
str(mu)

#plot the distribution of μ values at each height
# use type="n" to hide raw data
plot( height ~ weight , d2 , type="n" )
# loop over samples and plot each mu value
for ( i in 1:100 )
    points( weight.seq , mu[i,] , pch=16 , col=col.alpha(rangi2,0.1) )

#summarize the distribution for each weight value
# summarize the distribution of mu
mu.mean <- apply( mu , 2 , mean )
mu.HPDI <- apply( mu , 2 , HPDI , prob=0.89 )

# plot raw data
# fading out points to make line and interval more visible
plot( height ~ weight , data=d2 , col=col.alpha(rangi2,0.5) )
# plot the MAP line, aka the mean mu for each weight
lines( weight.seq , mu.mean )
# plot a shaded region for 89% HPDI
shade( mu.HPDI , weight.seq )
``` 





